#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Условное включение воркеров очереди через переменную окружения QUEUE_WORKER_ENABLED
if [ "$QUEUE_WORKER_ENABLED" = "true" ]; then
    echo "Queue workers enabled - activating laravel-worker.conf"
    if [ -f /etc/supervisor/conf.d/laravel-worker.conf.disabled ]; then
        mv /etc/supervisor/conf.d/laravel-worker.conf.disabled /etc/supervisor/conf.d/laravel-worker.conf
    fi
else
    echo "Queue workers disabled - deactivating laravel-worker.conf"
    if [ -f /etc/supervisor/conf.d/laravel-worker.conf ]; then
        mv /etc/supervisor/conf.d/laravel-worker.conf /etc/supervisor/conf.d/laravel-worker.conf.disabled
    fi
fi

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
